### ISSUE TITLE
Coverage report includes tests

### ISSUE THREAD

**Issue by kinday** [iamstarkov/generator-zen#10]
![image](https://cloud.githubusercontent.com/assets/1751980/10344854/564f983a-6d2e-11e5-86fb-42104970b38d.png)

Covering tests with tests seems too meta.

**Comment by kinday** [comment]
Default ignore paths are following: `**/node_modules/**`, `**/test/**`, `**/tests/**`.

I tried `mkdir test && mv test.js test/index.spec.js` and it resolved issue.

**Comment by iamstarkov** [comment]
do you think it should be added to isparta?

**Comment by iamstarkov** [comment]
cannot find the way to add it this exception to isparta. should it be added to istanbul?

**Comment by iamstarkov** [comment]
apparently babel-istanbul can help us
coverage script: https://github.com/iamstarkov/typographic-base/blob/master/package.json#L8
and coverage files list https://coveralls.io/builds/4256501

**Comment by iamstarkov** [comment]
@kinday @denysdovhan what do you think about switching to babel-istanbul?

**Comment by denysdovhan** [comment]
looks nice. Like a old good istanbul.

**Comment by iamstarkov** [comment]
can you try it in your several project to make sure it works as intended

**Comment by iamstarkov** [comment]
in this project babel-istanbul didnt work out https://github.com/talgautb/typographic-currency

**Comment by denysdovhan** [comment]
Why didn't?

**Comment by iamstarkov** [comment]
i dont know, it just didnt

**Comment by iamstarkov** [comment]
try it. I got zero coverage

**Comment by denysdovhan** [comment]
OK, but tomorrow

**Comment by kinday** [comment]
:+1:
