### ISSUE TITLE
TDD polling

### ISSUE THREAD

**Issue by kinday** [iamstarkov/generator-zen#35]
Polling leads to high CPU utilization* and it is recommended to use when watching files over network. Is there an issue which led to decision to set this flag by default? If not I’d suggest to remove it.

<sub>* It affects battery life and limits ability to develop on the go.</sub>

**Comment by iamstarkov** [comment]
mainly chokidar is supposed to work with tape as far as mocha and ava have built-in `watch` mode. I was thinking that the same convention among all three frameworks will be a good idea, but built-in modes work better than pure chokidar, so i will switch back to chokidar only for tape.

**Comment by iamstarkov** [comment]
back to polling: i have to use polling because for some reason chokidar have been triggered when i was just switching tabs in my editor. Turning on polling eliminated this problem

**Comment by iamstarkov** [comment]
do you still have a problem with it?

**Comment by iamstarkov** [comment]
just published `v2.1.6` where only `tape` uses chokidar directly

**Comment by iamstarkov** [comment]
seems to be not a problem anymore
